name: sunrise_sunset
description: Dart API that provides sunset and sunrise times for a given latitude and longitude
version: 1.0.0
authors: 
  - Aeyrium Inc. <diego@aeyrium.com>
  - Diego Vel√°squez <diego.velasquez.lopez@gmail.com>

homepage: https://aeyrium.com/
repository: https://github.com/aeyrium/sunrise-sunset

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter

